"""Add status field

Revision ID: 7c719845ba28
Revises: b0537b7cf272
Create Date: 2025-04-06 13:40:46.311071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c719845ba28'
down_revision = 'b0537b7cf272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
