"""add_new_cve_fields

Revision ID: d35ef2ed2938
Revises: 7c719845ba28
Create Date: 2025-04-06 15:40:58.939101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35ef2ed2938'
down_revision = '7c719845ba28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.Column('match_criteria_id', sa.String(length=50), nullable=False),
    sa.Column('vulnerable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['cve.cve_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_identifier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vuln_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('access_vector', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('access_complexity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('authentication', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidentiality_impact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('integrity_impact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('availability_impact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('base_severity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('exploitability_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('impact_score', sa.Float(), nullable=True))
        batch_op.drop_column('severity')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('impact_score')
        batch_op.drop_column('exploitability_score')
        batch_op.drop_column('base_severity')
        batch_op.drop_column('availability_impact')
        batch_op.drop_column('integrity_impact')
        batch_op.drop_column('confidentiality_impact')
        batch_op.drop_column('authentication')
        batch_op.drop_column('access_complexity')
        batch_op.drop_column('access_vector')
        batch_op.drop_column('vuln_status')
        batch_op.drop_column('source_identifier')

    op.drop_table('cpe')
    # ### end Alembic commands ###
